apiVersion: v1
kind: Secret
metadata:
  name: acrregistrykey
type: Opaque
data:
  docker-server: "{{ .Values.acr.dockerserver }}"
  docker-username: "{{ .Values.acr.dockerusername }}"
  docker-password: "{{ .Values.acr.dockerpassword }}"
  docker-email: "{{ .Values.acr.dockeremail }}"