apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-web
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: go-web
        app: go-web
    spec:
      containers:
      - name: go-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: SQLSERVER
          value: "{{ .Values.dbconfig.server }}"
        - name: SQLPORT
          value: "{{ .Values.dbconfig.port }}"
        - name: SQLID
          value: "{{ .Values.dbconfig.id }}"
        - name: SQLPWD
          value: "{{ .Values.dbconfig.pwd }}"
        - name: SQLDB
          value: "{{ .Values.dbconfig.dbname }}"
        ports:
          - containerPort: {{ .Values.service.internalPort }}